#!/bin/sh

#	Fill in the location of your libeth32.so and pk3 file in ETH32_DIR
export ETH32_DIR="/path/to/eth32"

#	Fill in the location of your perl scripts (defaults to eth32/scripts)
export ETH32_SCRIPTS="$ETH32_DIR/scripts"

#	Fill in the location of your Enemy Territory Installation
export ETH32_ET="/path/to/enemy-territory"

#	If you don't want to use auth, set this to true.
#	Note that you will not be able to communicate with your fellow cheaters
#	Nor can you see where they are, or use IRC.
#	If you just dont want to show in tracker, you can also select anonymous.
export ETH32_NO_AUTH="false"

#	you can ignore the rest :)
#
#

export LD_PRELOAD="$ETH32_DIR/libeth32_v3.so"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
cd $ETH32_ET
exec ./et.x86 "$@"
unset LD_PRELOAD
